[workspace]
members = [
    # zkVM interface
    "crates/zkvm-interface",
    # zkVMs
    "crates/ere-sp1",
    "crates/ere-risczero",
    "crates/ere-openvm",
    "crates/ere-pico",
    "crates/ere-jolt",
    "crates/ere-zisk",
    "crates/ere-airbender",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace.lints]

[workspace.dependencies]
# local dependencies
zkvm-interface = { path = "crates/zkvm-interface" }

[patch.crates-io]
# These patches are only needed by Jolt
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
