[workspace]
members = [
    "crates/build-utils",
    # zkVM interface
    "crates/zkvm-interface",
    # zkVMs
    "crates/ere-sp1",
    "crates/ere-risczero",
    "crates/ere-openvm",
    "crates/ere-pico",
    "crates/ere-nexus",
    "crates/ere-jolt",
    "crates/ere-zisk",

    # Guest compilers
    "docker/sp1",
]
resolver = "2"

exclude = ["tests"]


[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace.lints]

[workspace.dependencies]
tracing = "0.1.41"
tempfile = "3.3"
toml = "0.8"
clap = { version = "4.5.41", features = ["derive"] }
anyhow = "1.0"

# local dependencies
zkvm-interface = { path = "crates/zkvm-interface" }
build-utils = { path = "crates/build-utils" }

[patch.crates-io]
# These patches are only needed by Jolt
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "v0.5.0-optimize-mul-u64" }
