name: Test Airbender (Docker)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-airbender-via-docker-build:
    name: Build Airbender Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ere-base image
        run: |
          docker build \
            --tag ere-base:latest \
            --file docker/base/Dockerfile.base .

      - name: Build ere-builder-airbender image
        run: |
          docker build \
            --tag ere-builder-airbender:latest \
            --file docker/airbender/Dockerfile .
